export type ExpressiveSendStyles =
  | 'celebration'
  | 'shooting_star'
  | 'fireworks'
  | 'lasers'
  | 'love'
  | 'confetti'
  | 'balloons'
  | 'spotlight'
  | 'echo'
  | 'invisible'
  | 'gentle'
  | 'loud'
  | 'slam'
